export enum GemTypeNames {
	amethyst = 'amethyst',
	aquamarine = 'aquamarine',
	diamond = 'diamond',
	emerald = 'emerald',
	opal = 'opal',
	ruby = 'ruby',
	sapphire = 'sapphire',
	topaz = 'topaz',
	P = 'amethyst',
	Q = 'aquamarine',
	D = 'diamond',
	G = 'emerald',
	E = 'opal',
	R = 'ruby',
	B = 'sapphire',
	Y = 'topaz',
}

export enum GemTypeLetters {
	amethyst = 'P',
	aquamarine = 'Q',
	diamond = 'D',
	emerald = 'G',
	opal = 'E',
	ruby = 'R',
	sapphire = 'B',
	topaz = 'Y',
	P = 'P',
	Q = 'Q',
	D = 'D',
	G = 'G',
	E = 'E',
	R = 'R',
	B = 'B',
	Y = 'Y',
}
