import { ITowerType, TowerRarity } from '../data-models/tower-type-model';

const GemsBasic: { [ key: string ]: ITowerType } = {
	P1: {
		rarity: TowerRarity.Common,
		towerTypeId: 'P1',
		nameLong: 'Chipped Amethyst',
		assetName: 'GEM_P1',
		imgUrl: 'sprites/gems/gems_amethyst.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[]]
	},
	P2: {
		rarity: TowerRarity.Common,
		towerTypeId: 'P2',
		nameLong: 'Flawed Amethyst',
		assetName: 'GEM_P2',
		imgUrl: 'sprites/gems/gems_amethyst.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['P1', 'P1']]
	},
	P3: {
		rarity: TowerRarity.Common,
		towerTypeId: 'P3',
		nameLong: 'Normal Amethyst',
		assetName: 'GEM_P3',
		imgUrl: 'sprites/gems/gems_amethyst.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['P2', 'P2'], ['P1', 'P1', 'P1', 'P1']]
	},
	P4: {
		rarity: TowerRarity.Common,
		towerTypeId: 'P4',
		nameLong: 'Polished Amethyst',
		assetName: 'GEM_P4',
		imgUrl: 'sprites/gems/gems_amethyst.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['P3', 'P3'], ['P2', 'P2', 'P2', 'P2']]
	},
	P5: {
		rarity: TowerRarity.Common,
		towerTypeId: 'P5',
		nameLong: 'Perfect Amethyst',
		assetName: 'GEM_P5',
		imgUrl: 'sprites/gems/gems_amethyst.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['P4', 'P4'], ['P3', 'P3', 'P3', 'P3']]
	},
	Q1: {
		rarity: TowerRarity.Common,
		towerTypeId: 'Q1',
		nameLong: 'Chipped Aquamarine',
		assetName: 'GEM_Q1',
		imgUrl: 'sprites/gems/gems_aquamarine.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[]]
	},
	Q2: {
		rarity: TowerRarity.Common,
		towerTypeId: 'Q2',
		nameLong: 'Flawed Aquamarine',
		assetName: 'GEM_Q2',
		imgUrl: 'sprites/gems/gems_aquamarine.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['Q1', 'Q1']]
	},
	Q3: {
		rarity: TowerRarity.Common,
		towerTypeId: 'Q3',
		nameLong: 'Normal Aquamarine',
		assetName: 'GEM_Q3',
		imgUrl: 'sprites/gems/gems_aquamarine.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['Q2', 'Q2'], ['Q1', 'Q1', 'Q1', 'Q1']]
	},
	Q4: {
		rarity: TowerRarity.Common,
		towerTypeId: 'Q4',
		nameLong: 'Polished Aquamarine',
		assetName: 'GEM_Q4',
		imgUrl: 'sprites/gems/gems_aquamarine.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['Q3', 'Q3'], ['Q2', 'Q2', 'Q2', 'Q2']]
	},
	Q5: {
		rarity: TowerRarity.Common,
		towerTypeId: 'Q5',
		nameLong: 'Perfect Aquamarine',
		assetName: 'GEM_Q5',
		imgUrl: 'sprites/gems/gems_aquamarine.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['Q4', 'Q4'], ['Q3', 'Q3', 'Q3', 'Q3']]
	},

	D1: {
		rarity: TowerRarity.Common,
		towerTypeId: 'D1',
		nameLong: 'Chipped Diamond',
		assetName: 'GEM_D1',
		imgUrl: 'sprites/gems/gems_diamond.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[]]
	},
	D2: {
		rarity: TowerRarity.Common,
		towerTypeId: 'D2',
		nameLong: 'Flawed Diamond',
		assetName: 'GEM_D2',
		imgUrl: 'sprites/gems/gems_diamond.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['D1', 'D1']]
	},
	D3: {
		rarity: TowerRarity.Common,
		towerTypeId: 'D3',
		nameLong: 'Normal Diamond',
		assetName: 'GEM_D3',
		imgUrl: 'sprites/gems/gems_diamond.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['D2', 'D2'], ['D1', 'D1', 'D1', 'D1']]
	},
	D4: {
		rarity: TowerRarity.Common,
		towerTypeId: 'D4',
		nameLong: 'Polished Diamond',
		assetName: 'GEM_D4',
		imgUrl: 'sprites/gems/gems_diamond.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['D3', 'D3'], ['D2', 'D2', 'D2', 'D2']]
	},
	D5: {
		rarity: TowerRarity.Common,
		towerTypeId: 'D5',
		nameLong: 'Perfect Diamond',
		assetName: 'GEM_D5',
		imgUrl: 'sprites/gems/gems_diamond.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['D4', 'D4'], ['D3', 'D3', 'D3', 'D3']]
	},

	G1: {
		rarity: TowerRarity.Common,
		towerTypeId: 'G1',
		nameLong: 'Chipped Emerald',
		assetName: 'GEM_G1',
		imgUrl: 'sprites/gems/gems_emerald.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[]]
	},
	G2: {
		rarity: TowerRarity.Common,
		towerTypeId: 'G2',
		nameLong: 'Flawed Emerald',
		assetName: 'GEM_G2',
		imgUrl: 'sprites/gems/gems_emerald.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['G1', 'G1']]
	},
	G3: {
		rarity: TowerRarity.Common,
		towerTypeId: 'G3',
		nameLong: 'Normal Emerald',
		assetName: 'GEM_G3',
		imgUrl: 'sprites/gems/gems_emerald.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['G2', 'G2'], ['G1', 'G1', 'G1', 'G1']]
	},
	G4: {
		rarity: TowerRarity.Common,
		towerTypeId: 'G4',
		nameLong: 'Polished Emerald',
		assetName: 'GEM_G4',
		imgUrl: 'sprites/gems/gems_emerald.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['G3', 'G3'], ['G2', 'G2', 'G2', 'G2']]
	},
	G5: {
		rarity: TowerRarity.Common,
		towerTypeId: 'G5',
		nameLong: 'Perfect Emerald',
		assetName: 'GEM_G5',
		imgUrl: 'sprites/gems/gems_emerald.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['G4', 'G4'], ['G3', 'G3', 'G3', 'G3']]
	},

	E1: {
		rarity: TowerRarity.Common,
		towerTypeId: 'E1',
		nameLong: 'Chipped Opal',
		assetName: 'GEM_E1',
		imgUrl: 'sprites/gems/gems_opal.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[]]
	},
	E2: {
		rarity: TowerRarity.Common,
		towerTypeId: 'E2',
		nameLong: 'Flawed Opal',
		assetName: 'GEM_E2',
		imgUrl: 'sprites/gems/gems_opal.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['E1', 'E1']]
	},
	E3: {
		rarity: TowerRarity.Common,
		towerTypeId: 'E3',
		nameLong: 'Normal Opal',
		assetName: 'GEM_E3',
		imgUrl: 'sprites/gems/gems_opal.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['E2', 'E2'], ['E1', 'E1', 'E1', 'E1']]
	},
	E4: {
		rarity: TowerRarity.Common,
		towerTypeId: 'E4',
		nameLong: 'Polished Opal',
		assetName: 'GEM_E4',
		imgUrl: 'sprites/gems/gems_opal.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['E3', 'E3'], ['E2', 'E2', 'E2', 'E2']]
	},
	E5: {
		rarity: TowerRarity.Common,
		towerTypeId: 'E5',
		nameLong: 'Perfect Opal',
		assetName: 'GEM_E5',
		imgUrl: 'sprites/gems/gems_opal.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['E4', 'E4'], ['E3', 'E3', 'E3', 'E3']]
	},

	R1: {
		rarity: TowerRarity.Common,
		towerTypeId: 'R1',
		nameLong: 'Chipped Ruby',
		assetName: 'GEM_R1',
		imgUrl: 'sprites/gems/gems_ruby.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[]]
	},
	R2: {
		rarity: TowerRarity.Common,
		towerTypeId: 'R2',
		nameLong: 'Flawed Ruby',
		assetName: 'GEM_R2',
		imgUrl: 'sprites/gems/gems_ruby.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['R1', 'R1']]
	},
	R3: {
		rarity: TowerRarity.Common,
		towerTypeId: 'R3',
		nameLong: 'Normal Ruby',
		assetName: 'GEM_R3',
		imgUrl: 'sprites/gems/gems_ruby.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['R2', 'R2'], ['R1', 'R1', 'R1', 'R1']]
	},
	R4: {
		rarity: TowerRarity.Common,
		towerTypeId: 'R4',
		nameLong: 'Polished Ruby',
		assetName: 'GEM_R4',
		imgUrl: 'sprites/gems/gems_ruby.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['R3', 'R3'], ['R2', 'R2', 'R2', 'R2']]
	},
	R5: {
		rarity: TowerRarity.Common,
		towerTypeId: 'R5',
		nameLong: 'Perfect Ruby',
		assetName: 'GEM_R5',
		imgUrl: 'sprites/gems/gems_ruby.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['R4', 'R4'], ['R3', 'R3', 'R3', 'R3']]
	},

	B1: {
		rarity: TowerRarity.Common,
		towerTypeId: 'B1',
		nameLong: 'Chipped Sapphire',
		assetName: 'GEM_B1',
		imgUrl: 'sprites/gems/gems_sapphire.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[]]
	},
	B2: {
		rarity: TowerRarity.Common,
		towerTypeId: 'B2',
		nameLong: 'Flawed Sapphire',
		assetName: 'GEM_B2',
		imgUrl: 'sprites/gems/gems_sapphire.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['B1', 'B1']]
	},
	B3: {
		rarity: TowerRarity.Common,
		towerTypeId: 'B3',
		nameLong: 'Normal Sapphire',
		assetName: 'GEM_B3',
		imgUrl: 'sprites/gems/gems_sapphire.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['B2', 'B2'], ['B1', 'B1', 'B1', 'B1']]
	},
	B4: {
		rarity: TowerRarity.Common,
		towerTypeId: 'B4',
		nameLong: 'Polished Sapphire',
		assetName: 'GEM_B4',
		imgUrl: 'sprites/gems/gems_sapphire.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['B3', 'B3'], ['B2', 'B2', 'B2', 'B2']]
	},
	B5: {
		rarity: TowerRarity.Common,
		towerTypeId: 'B5',
		nameLong: 'Perfect Sapphire',
		assetName: 'GEM_B5',
		imgUrl: 'sprites/gems/gems_sapphire.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['B4', 'B4'], ['B3', 'B3', 'B3', 'B3']]
	},

	Y1: {
		rarity: TowerRarity.Common,
		towerTypeId: 'Y1',
		nameLong: 'Chipped Topaz',
		assetName: 'GEM_Y1',
		imgUrl: 'sprites/gems/gems_topaz.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[]]
	},
	Y2: {
		rarity: TowerRarity.Common,
		towerTypeId: 'Y2',
		nameLong: 'Flawed Topaz',
		assetName: 'GEM_Y2',
		imgUrl: 'sprites/gems/gems_topaz.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['Y1', 'Y1']]
	},
	Y3: {
		rarity: TowerRarity.Common,
		towerTypeId: 'Y3',
		nameLong: 'Normal Topaz',
		assetName: 'GEM_Y3',
		imgUrl: 'sprites/gems/gems_topaz.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['Y2', 'Y2'], ['Y1', 'Y1', 'Y1', 'Y1']]
	},
	Y4: {
		rarity: TowerRarity.Common,
		towerTypeId: 'Y4',
		nameLong: 'Polished Topaz',
		assetName: 'GEM_Y4',
		imgUrl: 'sprites/gems/gems_topaz.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['Y3', 'Y3'], ['Y2', 'Y2', 'Y2', 'Y2']]
	},
	Y5: {
		rarity: TowerRarity.Common,
		towerTypeId: 'Y5',
		nameLong: 'Perfect Topaz',
		assetName: 'GEM_Y5',
		imgUrl: 'sprites/gems/gems_topaz.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [['Y4', 'Y4'], ['Y3', 'Y3', 'Y3', 'Y3']]
	},
};

const GemsAdvanced: { [key: string ]: ITowerType } = {
	P6: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'P6',
		nameLong: 'Huge Amethyst',
		assetName: 'GEM_P6',
		imgUrl: 'sprites/gems/gems_amethyst.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'P5', 'P5' ], ['P4', 'P4', 'P4', 'P4']]
	},
	Q6: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'Q6',
		nameLong: 'Huge Aquamarine',
		assetName: 'GEM_Q6',
		imgUrl: 'sprites/gems/gems_aquamarine.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'Q5', 'Q5' ], ['Q4', 'Q4', 'Q4', 'Q4']]
	},
	D6: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'D6',
		nameLong: 'Huge Diamond',
		assetName: 'GEM_D6',
		imgUrl: 'sprites/gems/gems_diamond.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'D5', 'D5' ], ['D4', 'D4', 'D4', 'D4']]
	},
	G6: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'G6',
		nameLong: 'Huge Emerald',
		assetName: 'GEM_G6',
		imgUrl: 'sprites/gems/gems_emerald.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'G5', 'G5' ], ['G4', 'G4', 'G4', 'G4']]
	},
	E6: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'E6',
		nameLong: 'Huge Opal',
		assetName: 'GEM_E6',
		imgUrl: 'sprites/gems/gems_opal.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'E5', 'E5' ], ['E4', 'E4', 'E4', 'E4']]
	},
	R6: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'R6',
		nameLong: 'Huge Ruby',
		assetName: 'GEM_R6',
		imgUrl: 'sprites/gems/gems_ruby.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'R5', 'R5' ], ['R4', 'R4', 'R4', 'R4']]
	},
	B6: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'B6',
		nameLong: 'Huge Sapphire',
		assetName: 'GEM_B6',
		imgUrl: 'sprites/gems/gems_sapphire.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'B5', 'B5' ]]
	},
	Y6: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'Y6',
		nameLong: 'Huge Topaz',
		assetName: 'GEM_Y6',
		imgUrl: 'sprites/gems/gems_topaz.png',
		damage: 100,
		range: 10,
		speed: 4,
		splitShots: 3,
		buildCombinations: [[ 'Y5', 'Y5' ], ['Y4', 'Y4', 'Y4', 'Y4']]
	},
};

const TowersBasic: { [ key: string ]: ITowerType } = {
	Silver: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'Silver',
		nameLong: 'Silver',
		assetName: 'SILVER',
		imgUrl: 'sprites/towers/tower_silver.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'D1', 'B1', 'Y1' ]]
	},
	PinkDiamond: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'PinkDiamond',
		nameLong: 'Pink Diamond',
		assetName: 'PINK_DIAMOND',
		imgUrl: 'sprites/towers/tower_pink_diamond.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'D3', 'Y3', 'D5' ]]
	},
	Malachite: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'Malachite',
		nameLong: 'Malachite',
		assetName: 'MALACHITE',
		imgUrl: 'sprites/towers/tower_malachite.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'Y1', 'G1', 'Q1' ]]
	},
	AsteriatedRuby: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'AsteriatedRuby',
		nameLong: 'Asteriated Ruby',
		assetName: 'ASTERIATED_RUBY',
		imgUrl: 'sprites/towers/tower_asteriated_ruby.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'R2', 'R1', 'P1' ]]
	},
	Bloodstone: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'Bloodstone',
		nameLong: 'Bloodstone',
		assetName: 'BLOODSTONE',
		imgUrl: 'sprites/towers/tower_bloodstone.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'R5', 'Q4', 'P3' ]]
	},
	Quartz: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'Quartz',
		nameLong: 'Quartz',
		assetName: 'QUARTZ',
		imgUrl: 'sprites/towers/tower_quartz.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'G4', 'R3', 'P2' ]]
	},
	Jade: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'Jade',
		nameLong: 'Jade',
		assetName: 'JADE',
		imgUrl: 'sprites/towers/tower_jade.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'G3', 'E3', 'B2' ]]
	},
	DarkEmerald: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'DarkEmerald',
		nameLong: 'Dark Emerald',
		assetName: 'DARK_EMERALD',
		imgUrl: 'sprites/towers/tower_dark_emerald.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'G5', 'B4', 'Y2' ]]
	},
	Gold: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'Gold',
		nameLong: 'Gold',
		assetName: 'GOLD',
		imgUrl: 'sprites/towers/tower_gold.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'P5', 'P4', 'D2' ]]
	},
	ParaibaTourmaline: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'ParaibaTourmaline',
		nameLong: 'Paraiba Tourmaline',
		assetName: 'PARAIBA_TOURMALINE',
		imgUrl: 'sprites/towers/tower_paraiba_tourmaline.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'Q5', 'E4', 'G2' ]]
	},
	ChrysoberylCatsEye: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'ChrysoberylCatsEye',
		nameLong: `Chrysoberyl Cat's Eye`,
		assetName: 'CHRYSOBERYL_CATS_EYE',
		imgUrl: 'sprites/towers/tower_chrysoberyl_cats_eye.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'E5', 'D4', 'Q3' ]]
	},
	DeepseaPearl: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'DeepseaPearl',
		nameLong: 'Deepsea Pearl',
		assetName: 'DEEPSEA_PEARL',
		imgUrl: 'sprites/towers/tower_deepsea_pearl.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'Q4', 'D4', 'G2' ]]
	},
	YellowSapphire: {
		rarity: TowerRarity.Uncommon,
		towerTypeId: 'YellowSapphire',
		nameLong: 'Yellow Sapphire',
		assetName: 'YELLOW_SAPPHIRE',
		imgUrl: 'sprites/towers/tower_yellow_sapphire.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'B5', 'Y4', 'R4' ]]
	},
};

const TowersAdvanced: { [ key: string ]: ITowerType } = {
	SilverKnight: {
		rarity: TowerRarity.Rare,
		towerTypeId:  'SilverKnight',
		nameLong: 'Silver Knight',
		assetName: 'SILVER_KNIGHT',
		imgUrl: 'sprites/towers/tower_silver_knight.png',
		damage: 50,
		range: 6,
		speed: 2,
		splitShots: 1,
		buildCombinations: [[ 'Q2', 'R3', 'Silver' ]]
	},
	VividMalachite: {
		rarity: TowerRarity.Rare,
		towerTypeId: 'VividMalachite',
		nameLong: 'Vivid Malachite',
		assetName: 'VIVID_MALACHITE',
		imgUrl: 'sprites/towers/tower_vivid_malachite.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'Y3', 'D2', 'Malachite' ]]
	},
	Uranium238: {
		rarity: TowerRarity.Rare,
		towerTypeId: 'Uranium238',
		nameLong: 'Uranium-238',
		assetName: 'URANIUM_238',
		imgUrl: 'sprites/towers/tower_uranium_238.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'Y5', 'B3', 'E2' ]]
	},
	Volcano: {
		rarity: TowerRarity.Rare,
		towerTypeId: 'Volcano',
		nameLong: 'Volcano',
		assetName: 'VOLCANO',
		imgUrl: 'sprites/towers/tower_volcano.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'AsteriatedRuby', 'P3', 'R4' ]]
	},
	CharmingLazurite: {
		rarity: TowerRarity.Rare,
		towerTypeId: 'CharmingLazurite',
		nameLong: 'Charming Lazurite',
		assetName: 'CHARMING_LAZURITE',
		imgUrl: 'sprites/towers/tower_charming_lazurite.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'Quartz', 'E3', 'G3' ]]
	},
	LuckyChineseJade: {
		rarity: TowerRarity.Rare,
		towerTypeId: 'LuckyChineseJade',
		nameLong: 'Lucky Chinese Jade',
		assetName: 'LUCKY_CHINESE_JADE',
		imgUrl: 'sprites/towers/tower_lucky_chinese_jade.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'Jade', 'Quartz', 'G3' ]]
	},
	GreyJade: {
		rarity: TowerRarity.Rare,
		towerTypeId: 'GreyJade',
		nameLong: 'Grey Jade',
		assetName: 'GREY_JADE',
		imgUrl: 'sprites/towers/tower_grey_jade.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'Jade', 'B4', 'Q3' ]]
	},
	EmeraldGolem: {
		rarity: TowerRarity.Rare,
		towerTypeId:  'EmeraldGolem',
		nameLong: 'Emerald Golem',
		assetName: 'EMERALD_GOLEM',
		imgUrl: 'sprites/towers/tower_emerald_golem.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'DarkEmerald', 'Gold', 'D3' ]]
	},
	EgyptGold: {
		rarity: TowerRarity.Rare,
		towerTypeId: 'EgyptGold',
		nameLong: 'Egypt Gold',
		assetName: 'EGYPT_GOLD',
		imgUrl: 'sprites/towers/tower_egypt_gold.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'Gold', 'P5', 'Q2' ]]
	},
	RedCoral: {
		rarity: TowerRarity.Rare,
		towerTypeId: 'RedCoral',
		nameLong: 'Red Coral',
		assetName: 'RED_CORAL',
		imgUrl: 'sprites/towers/tower_red_coral.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'DeepseaPearl', 'ChrysoberylCatsEye', 'E4' ]]
	},
	ElaboratelyCarvedTourmaline: {
		rarity: TowerRarity.Rare,
		towerTypeId: 'ElaboratelyCarvedTourmaline',
		nameLong: 'Elaborately Carved Tourmaline',
		assetName: 'ELABORATELY_CARVED_TOURMALINE',
		imgUrl: 'sprites/towers/tower_elaborately_carved_tourmaline.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'DarkEmerald', 'ParaibaTourmaline', 'G2' ]]
	},
};
const TowersRare: { [ key: string ]: ITowerType } = {
	HugePinkDiamond: {
		rarity: TowerRarity.Advanced,
		towerTypeId: 'HugePinkDiamond',
		nameLong: 'Huge Pink Diamond',
		assetName: 'HUGE_PINK_DIAMOND',
		imgUrl: 'sprites/towers/tower_huge_pink_diamond.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'PinkDiamond', 'Silver', 'SilverKnight' ]]
	},
	Uranium235: {
		rarity: TowerRarity.Advanced,
		towerTypeId: 'Uranium235',
		nameLong: 'Uranium-235',
		assetName: 'URANIUM_235',
		imgUrl: 'sprites/towers/tower_uranium_235.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'Uranium238', 'VividMalachite', 'Malachite' ]]
	},
	MonkeyKingJade: {
		rarity: TowerRarity.Advanced,
		towerTypeId: 'MonkeyKingJade',
		nameLong: 'Monkey King Jade',
		assetName: 'MONKEY_KING_JADE',
		imgUrl: 'sprites/towers/tower_monkey_king_jade.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'GreyJade', 'G4', 'P2' ]]
	},
};

const TowersEpic: { [ key: string ]: ITowerType } = {
	AntiqueBloodstone: {
		rarity: TowerRarity.Legendary,
		towerTypeId: 'AntiqueBloodstone',
		nameLong: 'Antique Bloodstone',
		assetName: 'ANTIQUE_BLOODSTONE',
		imgUrl: 'sprites/towers/tower_antique_bloodstone.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'Bloodstone', 'Volcano', 'R2' ]]
	}
};
const TowersTop: { [ key: string ]: ITowerType } = {
	StarOfAdam: {
		rarity: TowerRarity.Legendary,
		towerTypeId: 'StarOfAdam',
		nameLong: 'The Star of Adam',
		assetName: 'STAR_OF_ADAM',
		imgUrl: 'sprites/towers/tower_star_of_adam.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'ElaboratelyCarvedTourmaline', 'G6', 'P6' ]]
	},
	CarmenLucia: {
		rarity: TowerRarity.Legendary,
		towerTypeId: 'CarmenLucia',
		nameLong: 'Carmen-Lucia',
		assetName: 'CARMEN_LUCIA',
		imgUrl: 'sprites/towers/tower_carmen_lucia.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'RedCoral', 'E6', 'Q6' ]]
	},
	KohinoorDiamond: {
		rarity: TowerRarity.Legendary,
		towerTypeId: 'KohinoorDiamond',
		nameLong: 'Koh-i-noor Diamond',
		assetName: 'KOHINOOR_DIAMOND',
		imgUrl: 'sprites/towers/tower_kohinoor_diamond.png',
		damage: 1000,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'HugePinkDiamond', 'D6', 'P6' ]]
	},
	TheCrownPrince: {
		rarity: TowerRarity.Legendary,
		towerTypeId: 'TheCrownPrince',
		nameLong: 'The Crown Prince',
		assetName: 'THE_CROWN_PRINCE',
		imgUrl: 'sprites/towers/tower_the_crown_prince.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'AntiqueBloodstone', 'R6', 'G6' ]]
	},
	DepletedKyparium: {
		rarity: TowerRarity.Legendary,
		towerTypeId: 'DepletedKyparium',
		nameLong: 'Depleted Kyparium',
		assetName: 'DEPLETED_KYPARIUM',
		imgUrl: 'sprites/towers/tower_depleted_kyparium.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'Uranium235', 'Y6', 'Q6' ]]
	},
};
const TowersOnehit: { [ key: string ]: ITowerType } = {
	Agate: {
		rarity: TowerRarity.Secret,
		towerTypeId: 'Agate',
		nameLong: 'Agate',
		assetName: 'Agate',
		imgUrl: 'sprites/towers/tower_agate.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'G5', 'E5', 'Q5' ]]
	},
	Obsidian: {
		rarity: TowerRarity.Secret,
		towerTypeId: 'Obsidian',
		nameLong: 'Obsidian',
		assetName: 'OBSIDIAN',
		imgUrl: 'sprites/towers/tower_obsidian.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'D5', 'B5', 'Y5' ]]
	},
	Eudialyte: {
		rarity: TowerRarity.Secret,
		towerTypeId: 'Eudialyte',
		nameLong: 'Eudialyte',
		assetName: 'EUDIALYTE',
		imgUrl: 'sprites/towers/tower_eudialyte.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'G5', 'B5', 'R5' ]]
	},
	Zircon: {
		rarity: TowerRarity.Secret,
		towerTypeId: 'Zircon',
		nameLong: 'Zircon',
		assetName: 'ZIRCON',
		imgUrl: 'sprites/towers/tower_zircon.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'B5', 'G5', 'B4', 'G4' ]]
	},
	TheBurningStone: {
		rarity: TowerRarity.Secret,
		towerTypeId: 'TheBurningStone',
		nameLong: 'The Burning Stone',
		assetName: 'THE_BURNING_STONE',
		imgUrl: 'sprites/towers/tower_the_burning_stone.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[ 'R5', 'G5', 'B4', 'G4' ]]
	},
	WingsStone: {
		rarity: TowerRarity.Secret,
		towerTypeId: 'WingsStone',
		nameLong: 'Wings Stone',
		assetName: 'WINGS_STONE',
		imgUrl: 'sprites/towers/tower_wings_stone.png',
		damage: 10,
		range: 4,
		speed: 1,
		splitShots: 1,
		buildCombinations: [[]]
	},
};

const TowersAll = {
	... GemsBasic,
	... GemsAdvanced,
	... TowersBasic,
	... TowersAdvanced,
	... TowersRare,
	... TowersEpic,
	... TowersTop,
	... TowersOnehit
};

export {
	GemsBasic,
	GemsAdvanced,
	TowersBasic,
	TowersAdvanced,
	TowersRare,
	TowersEpic,
	TowersTop,
	TowersOnehit,
	TowersAll,
};
